name: Kops tests

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 15 * * *" # every day

permissions:
  id-token: write
  contents: read

jobs:
  daily-kops:
    if: github.repository == 'aws/amazon-vpc-cni-k8s'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # refs/tags/v4.1.7
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # refs/tags/v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # refs/tags/v3.11.1
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # refs/tags/v5.0.1
        with:
          go-version: "1.24"
      - name: Set up tools
        run: |
          # Install ginkgo version from go.mod
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin/
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # refs/tags/v4.0.2
        with:
          role-to-assume: ${{ secrets.OSS_TEST_ROLE_ARN }}
          role-duration-seconds: 28800 # 8 hours
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Run kops tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.EKS_CLUSTER_ROLE_ARN }}
          RUN_CNI_INTEGRATION_TESTS: false
          RUN_KOPS_TEST: true
          K8S_VERSION: 1.33.0-beta.0
          KOPS_VERSION: v1.33.0-beta.1
          KOPS_RUN_TOO_NEW_VERSION: 1
        run: |
          ./scripts/run-integration-tests.sh
        if: always()
