name: Nightly Cron tests

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * *" # every night

permissions:
  id-token: write
  contents: read

jobs:
  nightly-cron-test:
    if: github.repository == 'aws/amazon-vpc-cni-k8s'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # refs/tags/v5.0.0
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # refs/tags/v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # refs/tags/v3.11.1
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # refs/tags/v6.0.0
        with:
          go-version: "1.25"
      - name: Set up tools
        run: |
          # Install ginkgo version from go.mod
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin/
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # refs/tags/v4.0.2
        with:
          role-to-assume: ${{ secrets.OSS_TEST_ROLE_ARN }}
          role-duration-seconds: 14400 # 4 hours
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Run e2e tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.EKS_CLUSTER_ROLE_ARN }}
          RUN_CONFORMANCE: true
        run: |
          ./scripts/run-integration-tests.sh
