# Repo owner must review the PR properly before trigger this workflow manually.
name: Manual Pull Request test

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: "PR number we want to run tests on"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  integration-test:
    if: github.event.inputs.pull_request_number != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.inputs.pull_request_number }}/merge"
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Set up tools
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo@latest
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin/
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OSS_TEST_ROLE_ARN }}
          role-duration-seconds: 7200
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Run e2e tests
        env:
          DISABLE_PROMPT: true
          S3_BUCKET_CREATE: false
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.EKS_CLUSTER_ROLE_ARN }}
          RUN_CONFORMANCE: true
        run: |
          ./scripts/run-integration-tests.sh
