name: VPC CNI Release

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  GITHUB_USERNAME: ${{ secrets.EKS_BOT_GITHUB_USERNAME }}
  GITHUB_TOKEN: ${{ secrets.EKS_BOT_GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # refs/tags/v5.0.0
        with:
          ref: "refs/tags/${{ github.event.release.tag_name }}"
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # refs/tags/v6.1.0
        with:
          go-version: "1.25"
      - name: Generate CNI YAML
        run: make generate-cni-yaml
      - name: Create eks-charts PR
        run: make ekscharts-sync-release
      - name: Create sample manifests PR
        run: make config-folder-sync
