name: Weekly Cron tests

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 16 * * 3" # every Wednesday

permissions:
  id-token: write
  contents: read

jobs:
  weekly-cron:
    if: github.repository == 'aws/amazon-vpc-cni-k8s'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # refs/tags/v6.0.1
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # refs/tags/v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # refs/tags/v3.11.1
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # refs/tags/v6.0.0
        with:
          go-version: "1.25"
      - name: Set up tools
        run: |
          # Install ginkgo version from go.mod
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin/
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # refs/tags/v4.0.2
        with:
          role-to-assume: ${{ secrets.OSS_TEST_ROLE_ARN }}
          role-duration-seconds: 28800 # 8 hours
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Run perf tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.EKS_CLUSTER_ROLE_ARN }}
          RUN_CNI_INTEGRATION_TESTS: false
          PERFORMANCE_TEST_S3_BUCKET_NAME: cni-performance-tests
          RUN_PERFORMANCE_TESTS: true
        run: |
          ./scripts/run-integration-tests.sh
        if: always()
      - name: Run bottlerocket tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.EKS_CLUSTER_ROLE_ARN }}
          RUN_CNI_INTEGRATION_TESTS: false
          RUN_BOTTLEROCKET_TEST: true
        run: |
          ./scripts/run-integration-tests.sh
        if: always()
